type: professional_standard
code: "07.007"
title: Специалист по процессному управлению
registration:
  reg_number: 1138
  minjust_date: 8 мая 2018 года
  mintrud_order: 17 апреля 2018 года N 248н
general_info:
  activity: "Деятельность по анализу, регламентированию, проектированию, оптимизации, автоматизации, внедрению и контролю процессов и административных регламентов организаций"
  purpose: "Повышение эффективности деятельности организаций путем разработки и усовершенствования их процессов и административных регламентов, в том числе с использованием современных информационных и телекоммуникационных технологий"
  okz:
  - code: 1213
    name: Руководители в области определения политики и планирования деятельности
  - code: 2421
    name: Аналитики систем управления и организации
  okved:
  - code: "70.22"
    name: Консультирование по вопросам коммерческой деятельности и управления
developers:
  responsible: "ПАО \"Магнитогорский металлургический комбинат\", город Магнитогорск, Челябинская область"
  director: Шиляев Павел Владимирович
  organizations:
  - "Ассоциация профессионалов управления бизнес-процессами, город Москва"
  - "НОЧУ \"Институт логистики и управления цепями поставок\", город Москва"
  - "ООО \"ЭЛКОД\", город Москва"
